Loading data

In [1]:
import pandas as pd

In [ ]:


movies = pd.read_csv('movies.csv')
movie_keywords = pd.read_csv('movie_keywords.csv')
movie_genres = pd.read_csv('movie_genres.csv')
genres = pd.read_csv('genres.csv')
crew = pd.read_csv('crew.csv')
cast = pd.read_csv('cast.csv')

TABLE 1 - MOVIES

In [ ]:
# print(movies.shape)
# movies.info()
# movies.describe()

NULL IMPUTATION

In [5]:
movies.isnull().sum()

movie_id             0
title                0
original_language    0
release_date         0
runtime              0
budget               0
revenue              0
popularity           0
vote_average         0
vote_count           0
status               0
overview             0
dtype: int64

DATA TYPE CHANGING

In [6]:
movies["release_date"] = pd.to_datetime(
    movies["release_date"],
    format="%Y-%m-%d"
)

In [5]:
movies.head()

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,165000000.0,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,160000000.0,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,220000000.0,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,185000000.0,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,237000000.0,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."

REMOVING DUPLIICATES

In [7]:
movies.duplicated().sum()
movies = movies.drop_duplicates()
#for checking
movies.duplicated().sum()

np.int64(0)

CHECKING FOR INCONSISTENT VALUES

In [8]:
# movies.info()

movies["original_language"].unique()
movies["status"].unique()

<ArrowStringArray>
['Released']
Length: 1, dtype: str

FINAL CHECKING

In [ ]:
# movies.isnull().sum()
# movies.duplicated().sum()

TABLE 2 - MOVIES_KEYWORDS

In [ ]:
# print(movie_keywords.shape)
# movie_keywords.info()
# movie_keywords.describe()

In [9]:
# NULL IMPUTATION

movie_keywords.isnull().sum()

movie_id        0
keyword_id      0
keyword_name    0
dtype: int64

In [10]:

# REMOVING DUPLICATES

movie_keywords.duplicated().sum()
movie_keywords = movie_keywords.drop_duplicates()
#for checking
movie_keywords.duplicated().sum()

np.int64(0)

In [11]:
# CHECKING FOR INCONSISTENT VALUES
movie_keywords.head()
movie_keywords["keyword_id"].unique()
movie_keywords["movie_id"].unique()
movie_keywords["keyword_name"].unique()
movie_keywords["keyword_name"].value_counts()

keyword_name
based on novel or book    449
sequel                    416
duringcreditsstinger      296
aftercreditsstinger       242
murder                    176
                         ...
tween girl                  1
american tourist            1
salamanca, spain            1
international news          1
brutal deaths               1
Name: count, Length: 10288, dtype: int64

TABLE 3 - MOVIE_GENRES

In [12]:
# print(movie_genres.shape)
movie_genres.info()
# movie_keywords.describe()

<class 'pandas.DataFrame'>
RangeIndex: 6888 entries, 0 to 6887
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  6888 non-null   int64
 1   genre_id  6888 non-null   int64
dtypes: int64(2)
memory usage: 107.8 KB

In [13]:
# NULL IMPUTATION

movie_genres.isnull().sum()

# REMOVING DUPLICATES

movie_genres.duplicated().sum()
movie_genres = movie_genres.drop_duplicates()
#for checking
movie_genres.duplicated().sum()

np.int64(0)

In [14]:
movie_genres["movie_id"].unique()
movie_genres["genre_id"].unique()
movie_genres["movie_id"].value_counts()
movie_genres["genre_id"].unique()

array([   12,    18,   878,    28,    80,    53,    35, 10749,    14,
          37,  9648, 10752,    16, 10751, 10402,    27,    36, 10770,
          99])

TABLE - 4

In [15]:
crew.info()
crew.head()

<class 'pandas.DataFrame'>
RangeIndex: 7297 entries, 0 to 7296
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   crew_row_id  7297 non-null   int64
 1   movie_id     7297 non-null   int64
 2   person_id    7297 non-null   int64
 3   person_name  7297 non-null   str
 4   job          7297 non-null   str
 5   department   7297 non-null   str
dtypes: int64(3), str(3)
memory usage: 552.0 KB

   crew_row_id  movie_id  person_id        person_name       job department
0            1    157336        527     Jonathan Nolan    Writer    Writing
1            2    157336        525  Christopher Nolan    Writer    Writing
2            3    157336        525  Christopher Nolan  Director  Directing
3            4     27205        525  Christopher Nolan    Writer    Writing
4            5     27205        525  Christopher Nolan  Director  Directing

In [16]:
# NULL IMPUTATION

crew.isnull().sum()

# REMOVING DUPLICATES

crew.duplicated().sum()
crew = crew.drop_duplicates()

In [17]:
# Check unique values
crew["person_name"].unique()
crew["job"].unique()
crew["department"].unique()

# Check extra spaces
(crew["person_name"] != crew["person_name"].str.strip()).sum()
(crew["job"] != crew["job"].str.strip()).sum()
(crew["department"] != crew["department"].str.strip()).sum()

np.int64(0)

table - 5

In [18]:
# NULL IMPUTATION

cast.isnull().sum()
cast["character_name"] = cast["character_name"].fillna("Unknown")
# cast.head()

In [19]:
# REMOVING DUPLICATES

crew.duplicated().sum()
crew = crew.drop_duplicates()

TABLE 6

In [20]:
genres.head()

   genre_id genre_name
0        28     Action
1        12  Adventure
2        16  Animation
3        35     Comedy
4        80      Crime

In [21]:
# NULL IMPUTATION

genres.isnull().sum()

genre_id      0
genre_name    0
dtype: int64

In [22]:
# REMOVING DUPLICATES

genres.duplicated().sum()

np.int64(0)

remove orphaned rows

In [23]:
movie_genres = movie_genres[movie_genres["movie_id"].isin(movies["movie_id"])]
cast = cast[cast["movie_id"].isin(movies["movie_id"])]
crew = crew[crew["movie_id"].isin(movies["movie_id"])]
movie_keywords = movie_keywords[movie_keywords["movie_id"].isin(movies["movie_id"])]

In [24]:
movies["budget"].eq(0).sum()
movies["revenue"].eq(0).sum()

np.int64(102)

In [25]:
movies["budget"] = movies["budget"].replace(0, pd.NA)
movies["revenue"] = movies["revenue"].replace(0, pd.NA)

Loading data into SQl TABLE

In [4]:
import pymysql
conn = pymysql.connect(
    host = 'localhost',
    user = 'root',
    password = 'root',
    database = 'TMDB'
)
cursor = conn.cursor()

In [3]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:root@localhost/TMDB')

In [ ]:
movies.to_sql('movies', if_exists='replace', con=engine, index=False)
genres.to_sql("genres", engine, if_exists="replace", index=False)
movie_genres.to_sql("movie_genres", engine, if_exists="replace", index=False)
cast.to_sql("cast", engine, if_exists="replace", index=False)
crew.to_sql("crew", engine, if_exists="replace", index=False)
movie_keywords.to_sql("movie_keywords", engine, if_exists="replace", index=False)

2503

In [2]:
#CHECKING
from sqlalchemy import inspect, text
inspector = inspect(engine)
print(inspector.get_table_names())

NameError: name 'engine' is not defined

In [8]:
query = text("""
    SELECT 
        m.title,
        g.genre_name
    FROM movies m
    JOIN movie_genres mg
        ON m.movie_id = mg.movie_id
    JOIN genres g
        ON mg.genre_id = g.genre_id
    LIMIT 10
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

print(result)

             title       genre_name
0     Interstellar  Science Fiction
1     Interstellar            Drama
2     Interstellar        Adventure
3        Inception        Adventure
4        Inception  Science Fiction
5        Inception           Action
6     The Avengers        Adventure
7     The Avengers           Action
8     The Avengers  Science Fiction
9  The Dark Knight         Thriller