CONNECTING TO DATABASE

In [1]:
import pymysql
from sqlalchemy import create_engine, text
import pandas as pd

In [5]:

conn = pymysql.connect(
    host = 'localhost',
    user = 'root',
    password = 'root',
    database = 'TMDB'
)
cursor = conn.cursor()

In [6]:

engine = create_engine('mysql+pymysql://root:root@localhost/TMDB')

QUESTION - 1

In [12]:
query = text("""
SELECT 
    m.title,
    m.release_date
FROM movies m
JOIN movie_genres mg 
    ON m.movie_id = mg.movie_id
JOIN genres g 
    ON mg.genre_id = g.genre_id
WHERE g.genre_name = 'Action'
  AND m.release_date > '2015-12-31';
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

                          title release_date
0                      Deadpool   2016-02-09
1        Avengers: Infinity War   2018-04-25
2             Avengers: Endgame   2019-04-24
3    Captain America: Civil War   2016-04-27
4                 Black Panther   2018-02-13
..                          ...          ...
263                  Peppermint   2018-09-06
264            Mortal Kombat II   2026-05-06
265                   Day Shift   2022-08-05
266                   Samaritan   2022-08-25
267                     Ghosted   2023-04-18

[268 rows x 2 columns]

QUESTION - 2

In [11]:
query = text("""
SELECT 
    m.title,
    m.revenue,
    g.genre_name
FROM movies m
JOIN movie_genres mg 
    ON m.movie_id = mg.movie_id
JOIN genres g 
    ON mg.genre_id = g.genre_id
ORDER BY m.revenue DESC
LIMIT 10;
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

                      title       revenue       genre_name
0                    Avatar  2.923706e+09           Action
1                    Avatar  2.923706e+09        Adventure
2                    Avatar  2.923706e+09  Science Fiction
3         Avengers: Endgame  2.799439e+09           Action
4         Avengers: Endgame  2.799439e+09        Adventure
5         Avengers: Endgame  2.799439e+09  Science Fiction
6  Avatar: The Way of Water  2.334485e+09           Action
7  Avatar: The Way of Water  2.334485e+09        Adventure
8  Avatar: The Way of Water  2.334485e+09  Science Fiction
9                   Titanic  2.264162e+09            Drama

QUESTION - 3

In [10]:
query = text("""
SELECT 
    g.genre_name,
    AVG(m.budget) AS average_budget,
    AVG(m.revenue) AS average_revenue
FROM movies m
JOIN movie_genres mg 
    ON m.movie_id = mg.movie_id
JOIN genres g 
    ON mg.genre_id = g.genre_id
GROUP BY g.genre_name
ORDER BY average_revenue DESC;
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

         genre_name  average_budget  average_revenue
0         Adventure    1.106736e+08     4.003113e+08
1         Animation    8.763551e+07     3.718357e+08
2            Family    8.790630e+07     3.533691e+08
3   Science Fiction    9.672225e+07     3.336488e+08
4            Action    9.422751e+07     3.084532e+08
5           Fantasy    8.864007e+07     3.027060e+08
6            Comedy    5.450018e+07     2.215264e+08
7             Music    4.281702e+07     2.015662e+08
8           Romance    3.693970e+07     1.748110e+08
9          Thriller    5.121405e+07     1.680042e+08
10              War    5.527116e+07     1.660915e+08
11            Crime    4.660846e+07     1.519315e+08
12          Mystery    3.795834e+07     1.446581e+08
13            Drama    3.996081e+07     1.435529e+08
14          Western    5.574839e+07     1.435406e+08
15          History    5.353273e+07     1.417206e+08
16           Horror    2.594464e+07     1.142054e+08
17         TV Movie    5.600000e+06     3.746000e+03
18      Documentary             NaN              NaN

QUESTION - 4

In [13]:
query = text("""
SELECT 
    actor_name,
    COUNT(DISTINCT movie_id) AS movie_count
FROM cast
GROUP BY actor_name
ORDER BY movie_count DESC
LIMIT 10;
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

           actor_name  movie_count
0   Samuel L. Jackson           39
1      Robert De Niro           38
2           Brad Pitt           38
3         Johnny Depp           37
4           Tom Hanks           33
5  Scarlett Johansson           32
6        Willem Dafoe           32
7       Mark Wahlberg           32
8          Tom Cruise           31
9      Morgan Freeman           31

QUESTION - 5

In [15]:
query = text("""
SELECT 
    person_name AS director_name,
    COUNT(DISTINCT movie_id) AS movie_count
FROM crew
WHERE job = 'Director'
GROUP BY person_name
HAVING COUNT(DISTINCT movie_id) > 3
ORDER BY movie_count DESC;
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

        director_name  movie_count
0    Steven Spielberg           27
1        Ridley Scott           19
2          Tim Burton           19
3     Martin Scorsese           16
4         Michael Bay           15
..                ...          ...
212   Stephen Sommers            4
213       Tate Taylor            4
214       Tim Johnson            4
215         Tim Story            4
216          Wes Ball            4

[217 rows x 2 columns]

QUESTION - 6

In [16]:
query = text("""
SELECT 
    keyword_name,
    COUNT(DISTINCT movie_id) AS movie_count
FROM movie_keywords
GROUP BY keyword_name
ORDER BY movie_count DESC
LIMIT 10;
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

             keyword_name  movie_count
0  based on novel or book          449
1                  sequel          416
2    duringcreditsstinger          296
3     aftercreditsstinger          242
4                  murder          176
5     based on true story          166
6           new york city          161
7                 villain          160
8            3d animation          155
9          based on comic          154

QUESTION - 7

In [17]:
query = text("""
SELECT 
    title,
    budget,
    revenue
FROM movies
WHERE budget > (
    SELECT AVG(budget)
    FROM movies
)
AND revenue < (
    SELECT AVG(revenue)
    FROM movies
);
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

                                  title        budget       revenue
0                            Fight Club  6.300000e+07  1.008538e+08
1                                  Fury  6.800000e+07  2.118179e+08
2                                Zodiac  6.500000e+07  8.478591e+07
3                                  Soul  1.500000e+08  1.219775e+08
4                            Braveheart  7.200000e+07  2.132162e+08
..                                  ...           ...           ...
268  The Nutcracker and the Four Realms  1.200000e+08  1.739611e+08
269                       Jack and Jill  7.900000e+07  1.497000e+08
270                           Samaritan  1.000000e+08  7.500000e+07
271         Ghostbusters: Frozen Empire  1.000000e+08  2.019675e+08
272                          Date Night  9.321480e+07  8.759568e+07

[273 rows x 3 columns]

QUESTION - 8

In [19]:
query = text("""
SELECT DISTINCT
    c.actor_name
FROM cast c
JOIN crew cr 
    ON c.movie_id = cr.movie_id
WHERE cr.person_name = 'Christopher Nolan'
  AND cr.job = 'Director';
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

             actor_name
0   Matthew McConaughey
1         Anne Hathaway
2         Michael Caine
3      Jessica Chastain
4         Casey Affleck
..                  ...
79           Nicky Katt
80          Paul Dooley
81     Jonathan Jackson
82         Larry Holden
83   Katharine Isabelle

[84 rows x 1 columns]

QUESTION - 9

In [21]:
query = text("""
SELECT 
    g.genre_name,
    AVG(m.vote_average) AS average_rating,
    COUNT(DISTINCT m.movie_id) AS movie_count
FROM movies m
JOIN movie_genres mg 
    ON m.movie_id = mg.movie_id
JOIN genres g 
    ON mg.genre_id = g.genre_id
GROUP BY g.genre_name
HAVING COUNT(DISTINCT m.movie_id) >= 20
ORDER BY average_rating DESC
LIMIT 1;
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

  genre_name  average_rating  movie_count
0        War        7.357576           85

QUESTION - 10

In [23]:
query = text("""
SELECT 
    m.title,
    COUNT(mk.keyword_id) AS keyword_count
FROM movies m
JOIN movie_keywords mk 
    ON m.movie_id = mk.movie_id
GROUP BY m.movie_id, m.title
ORDER BY keyword_count DESC
LIMIT 10;
""")

with engine.connect() as connection:
    result = pd.read_sql(query, connection)

result

                                        title  keyword_count
0                                     Smile 2             98
1                                     Taken 3             70
2                                 Silent Hill             63
3                              Twelve Monkeys             57
4              War for the Planet of the Apes             54
5                                 The Shining             52
6              Dawn of the Planet of the Apes             51
7                    How to Train Your Dragon             50
8  How to Train Your Dragon: The Hidden World             49
9                       Pacific Rim: Uprising             49