PANDAS ANALYSIS

In [1]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine, text

In [2]:
engine = create_engine('mysql+pymysql://root:root@localhost/TMDB')

In [10]:
movies = pd.read_sql("SELECT * FROM movies", engine)
movie_keywords = pd.read_sql("SELECT * FROM movie_keywords", engine)
movie_genres = pd.read_sql("SELECT * FROM movie_genres", engine)
genres = pd.read_sql("SELECT * FROM genres", engine)
crew = pd.read_sql("SELECT * FROM crew", engine)
cast = pd.read_sql("SELECT * FROM cast", engine)

QUESTION - 1

In [15]:
movies["movie_id"].nunique()
genres["genre_id"].nunique()
cast["person_id"].nunique()
crew["person_id"].nunique()

2848

QUESTION - 2

In [19]:
movies["budget"].isnull().sum()
movies["revenue"].isnull().sum()

(movies["budget"] == 0).sum()
(movies["revenue"] == 0).sum()

np.int64(0)

In [20]:
movies[
    (movies["budget"].isnull()) |
    (movies["revenue"].isnull()) |
    (movies["budget"] == 0) |
    (movies["revenue"] == 0)
][["title", "budget", "revenue"]]

                                  title       budget    revenue
324        Zack Snyder's Justice League   70000000.0        NaN
340                            Bird Box   19800000.0        NaN
403                            365 Days          NaN  9458590.0
468   To All the Boys I've Loved Before          NaN        NaN
554                                Prey   65000000.0        NaN
...                                 ...          ...        ...
2469                          Day Shift  100000000.0        NaN
2471                     A Serbian Film          NaN        NaN
2480                  Chungking Express     160000.0        NaN
2481      I'm Thinking of Ending Things          NaN        NaN
2491                            Ghosted   40000000.0        NaN

[133 rows x 3 columns]

QUESTION - 3

In [23]:
valid = movies[
    (movies["budget"] > 0) &
    (movies["revenue"] > 0)
].copy()

valid["profit"] = valid["revenue"] - valid["budget"]

valid["roi"] = (
    (valid["revenue"] - valid["budget"])
    / valid["budget"]
) * 100

valid[["title", "budget", "revenue", "profit", "roi"]].head(10)

,title,budget,revenue,profit,roi
0,Interstellar,165000000.0,7.466067e+08,5.816067e+08,352.488913
1,Inception,160000000.0,8.390306e+08,6.790306e+08,424.394144
2,The Avengers,220000000.0,1.518816e+09,1.298816e+09,590.370689
3,The Dark Knight,185000000.0,1.004558e+09,8.195584e+08,443.004564
4,Avatar,237000000.0,2.923706e+09,2.686706e+09,1133.631235
5,Deadpool,58000000.0,7.828373e+08,7.248373e+08,1249.719564
6,Fight Club,63000000.0,1.008538e+08,3.785375e+07,60.085322
7,Avengers: Infinity War,300000000.0,2.052415e+09,1.752415e+09,584.138346
8,The Shawshank Redemption,25000000.0,2.834147e+07,3.341469e+06,13.365876
9,Pulp Fiction,8000000.0,2.139288e+08,2.059288e+08,2574.109525

QUESTION - 4

In [24]:
top_roi = valid[
    valid["budget"] >= 1_000_000
].sort_values(
    "roi",
    ascending=False
).head(15)

top_roi[["title", "budget", "revenue", "roi"]]

                                title      budget      revenue           roi
1767         Dragon Ball Super: Broly   1000000.0  125002821.0  12400.282100
535   Snow White and the Seven Dwarfs   1488423.0  184925486.0  12324.256142
1791    The Rocky Horror Picture Show   1400000.0  171181400.0  12127.242857
467                             Rocky   1000000.0  117253345.0  11625.334500
1227               Gone with the Wind   4000000.0  402352579.0   9958.814475
716                   The Jungle Book   4000000.0  378000000.0   9350.000000
635                        Cinderella   2900000.0  263600000.0   8989.655172
372                               Saw   1200000.0  104045735.0   8570.477917
719    One Hundred and One Dalmatians   3600000.0  303000000.0   8316.666667
263        E.T. the Extra-Terrestrial  10500000.0  797307407.0   7493.403876
2399         My Big Fat Greek Wedding   5000000.0  368744044.0   7274.880880
43                          Star Wars  11000000.0  775398007.0   6949.072791
274                              Jaws   7000000.0  470653000.0   6623.614286
608                         Insidious   1500000.0  100106454.0   6573.763600
569                            Grease   6000000.0  396271103.0   6504.518383

QUESTION - 5

In [27]:
movies["release_year"] = movies["release_date"].dt.year

movies_per_year = (
    movies.groupby("release_year")
    .size()
    .sort_values(ascending=False)
)

movies_per_year.head(1)

release_year
2016    121
dtype: int64

QUESTION - 6

In [29]:
Q1 = movies["runtime"].quantile(0.25)
Q3 = movies["runtime"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

runtime_outliers = movies[
    (movies["runtime"] < lower) |
    (movies["runtime"] > upper)
]

runtime_outliers[["title", "runtime"]].head(5)

                                                title  runtime
0                                        Interstellar      169
16                                  Avengers: Endgame      181
18  The Lord of the Rings: The Fellowship of the Ring      179
19                                            Titanic      194
20      The Lord of the Rings: The Return of the King      201

QUESTION - 7

In [30]:
primary_genre = movie_genres.drop_duplicates(
    subset="movie_id",
    keep="first"
)

In [31]:
primary_genre = primary_genre.merge(
    genres,
    on="genre_id",
    how="left"
)

In [32]:
primary_genre = primary_genre.merge(
    movies[["movie_id", "title", "popularity"]],
    on="movie_id",
    how="left"
)

In [33]:
primary_genre_analysis = (
    primary_genre
    .groupby("genre_name")["popularity"]
    .mean()
    .sort_values(ascending=False)
)

primary_genre_analysis

genre_name
Science Fiction    21.261836
Music              18.324340
Animation          16.811212
Family             16.710635
Action             16.385188
War                15.470317
Horror             14.851835
Adventure          14.785510
Fantasy            13.022920
Mystery            12.427131
Western            12.322680
Thriller           11.294211
Drama              11.278534
Crime              10.739498
History            10.414567
Comedy              9.984262
Romance             9.976708
Documentary         7.726200
Name: popularity, dtype: float64

QUESTION - 8

In [34]:
actor_stats = (
    cast.groupby("actor_name")["movie_id"]
    .nunique()
    .reset_index(name="movie_count")
)

actor_data = cast.merge(
    movies[["movie_id", "vote_average"]],
    on="movie_id",
    how="left"
)

In [36]:
actor_stats = (
    actor_data.groupby("actor_name")
    .agg(
        movie_count=("movie_id", "nunique"),
        average_rating=("vote_average", "mean")
    )
    .sort_values("movie_count", ascending=False)
    .head(10)
)

actor_stats

                    movie_count  average_rating
actor_name
Samuel L. Jackson            39        6.938692
Robert De Niro               38        7.228316
Brad Pitt                    38        7.257289
Johnny Depp                  37        6.856973
Tom Hanks                    33        7.289758
Willem Dafoe                 32        7.114781
Mark Wahlberg                32        6.630063
Scarlett Johansson           32        7.056344
Tom Cruise                   31        7.040613
Morgan Freeman               31        6.963742

QUESTION - 9

In [37]:
duplicate_titles = movies[
    movies["title"].duplicated(keep=False)
].sort_values("title")

duplicate_titles[
    ["title", "release_date"]
]

                          title release_date
878   A Nightmare on Elm Street   1984-11-09
1928  A Nightmare on Elm Street   2010-04-30
261                     Aladdin   1992-11-25
339                     Aladdin   2019-05-22
166         Alice in Wonderland   2010-03-03
...                         ...          ...
1737                  The Thing   2011-10-12
744                Total Recall   1990-06-01
860                Total Recall   2012-08-02
252                Transformers   2007-06-27
2500               Transformers   1987-06-27

[100 rows x 2 columns]

QUESTION - 10

In [41]:
!pip install scipy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scipy in c:\users\acer\appdata\roaming\python\python314\site-packages (1.18.1)
Requirement already satisfied: numpy<2.8,>=2.0.0 in c:\users\acer\appdata\roaming\python\python314\site-packages (from scipy) (2.4.2)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
high_popularity = movies["popularity"].quantile(0.90)
low_popularity = movies["popularity"].quantile(0.10)

high_votes = movies["vote_count"].quantile(0.90)
low_votes = movies["vote_count"].quantile(0.10)

high_pop_low_votes = movies[
    (movies["popularity"] >= high_popularity) &
    (movies["vote_count"] <= low_votes)
]

low_pop_high_votes = movies[
    (movies["popularity"] <= low_popularity) &
    (movies["vote_count"] >= high_votes)
]

unusual_movies = pd.concat([
    high_pop_low_votes,
    low_pop_high_votes
])

unusual_movies[["title", "popularity", "vote_count"]]

                       title  popularity  vote_count
2248               Backrooms    258.4743        2483
2265               Companion     23.1407        2466
2295  Lee Cronin's The Mummy     79.4601        2430
2306       Kraven the Hunter     26.1998        2419
2388          Disclosure Day    394.3346        2328
2441                  Lolita     27.5391        2271
2452        Mortal Kombat II     99.5231        2260
2457                 Smile 2     23.7112        2256
2493           Lilo & Stitch     33.2161        2228
205       X-Men: First Class      1.2614       13680
244               Home Alone      1.8114       12658